version: "3"
services:
  redis:
    image: redis:6
    restart: on-failure:3
    container_name: redis
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      #   - redis-data-volume:/var/lib/redis
      #   - redis-data-volume2:/usr/local/var/db/redis/
    ports:
      - 6379:6379
    networks :
      - practice-project-network
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel debug
  
  mongo:
    image: mongo:4.2
    restart: on-failure:3
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: passport-app
    ports: 
      - 17017:27017
    expose: 
      - 27017
    networks :
      - practice-project-network
    volumes: 
      - mongodb-data-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mysql:
    image : mysql:5.7
    container_name: mysql
    restart: on-failure:3
    environment :
      MYSQL_DATABASE: "passport-practice"
      MYSQL_ROOT_PASSWORD : "7825tanmay"
      MYSQL_PASSWORD : "7825tanmay"
      MYSQL_USER : "tanmay"
    ports :
      - 13306:3306
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - mysql-plugin-volume:/usr/lib/mysql/plugin
    external_links:
      - redis:6379
    depends_on:
      - redis
    networks :
      - practice-project-network
    expose: 
      - 3306

  practice-project:
    build: .
    container_name: practice-project
    restart: on-failure:3
    expose:
      - 3000
    environment: 
      - MONGODB_CONNECTION_STRING=mongodb://tanmay:7825tanmay@mongo:27017/passport-app
      - MY_SQL_HOST=mysql
      - REDIS_HOST=redis
    external_links: 
      - mysql:3306
      - redis:6379
      - mongo:27017
    depends_on:
      - mysql
      - mongo
      - redis
    networks :
      - practice-project-network

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    external_links:
      - practice-project:3000
    depends_on: 
      - practice-project
    networks :
      - practice-project-network

# Names our volume
volumes:
  mysql-data-volume:
    driver: local
  mysql-plugin-volume:
    driver: local
  mongodb-data-volume:
    driver: local
  redis-data-volume:
    driver: local
  redis-data-volume2:
    driver: local
  redis-data:
    driver: local

networks :
  practice-project-network :
    driver : bridge 