version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    external_links:
      - practice-project:3000
    
  redis:
    image: redis
    command: 
      - redis-server /usr/local/etc/redis/redis.conf
      # - sudo apt-get install -y make wget gcc git
      # - sudo apt-get install -y libmariadb-dev
      # - git clone https://github.com/Ideonella-sakaiensis/lib_mysqludf_redis.git
      # - cd lib_mysqludf_redis/
      # - make
      # - make install 
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ~/redis-data:/var/lib/redis

    ports:
      - "6379:6379"

  practice-project:
    build: .
    container_name: practice-project
    expose:
      - "3000"