version: "3"
services:
  redis_service:
    image: redis
    container_name: redis_service
    command: 
      - redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ~/redis-data:/var/lib/redis
    ports:
      - 6379:6379
    networks :
      - practice-project-network

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    external_links:
      - practice-project:3000
    depends_on: 
      - "practice-project"
    networks :
      - practice-project-network

  mysql-database:
    image : mysql:5.7
    restart: unless-stopped
    container_name: mysql-database
    expose:
      # Opens port 3306 on the container
      - "3306"
    environment :
      MYSQL_DATABASE: "passport-practice"
      MYSQL_ROOT_PASSWORD : "7825tanmay"
      MYSQL_PASSWORD : "7825tanmay"
      MYSQL_USER : "tanmay"
    ports :
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    external_links:
      - redis_service
    depends_on:
      - "redis_service"
    networks :
      - practice-project-network

  practice-project:
    build: .
    container_name: practice-project
    restart: unless-stopped
    expose:
      - "3000"
    external_links: 
      - mysql-database:3306
      - redis
    depends_on:
      - "mysql-database"
    networks :
      - practice-project-network

# Names our volume
volumes:
  my-db:
    driver: local

networks :
  practice-project-network :
    driver : bridge 